# Final interference subjects for TMCJ-Contact  
## With justified 2Dmesh -> cartilage parameters

In [2]:
import pandas as pd
import numpy as np

from phd_helpers.paths import bone_pair_pose_intersection

### Load the interference check for tpm and mc1 for final 2Dmesh params 
 - From: '../BonePrep/Interference/Interference-box.ipynb'

In [3]:
df = pd.read_csv('../BonePrep/Interference/Interference-SmoothRemesh/tpm-mc1.csv', index_col=0)
df

,50037-L,50090-R,15294-R,50053-R,50049-R,15737-R,50061-R,14726-R,50016-L,14613-R,...,50000-R,50007-L,50014-R,14827-L,14818-R,14548-R,15882-R,15282-R,50045-R,14685-R
adduction,False,False,False,False,False,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
abduction,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,True,True,False,False
flexion,False,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,False
extension,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
pinch,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
grasp,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
jar,False,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,False
pinch_load,False,False,False,False,False,True,True,False,False,False,...,False,False,False,False,False,True,True,False,False,True
grasp_load,False,False,False,False,False,False,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False
jar_load,False,False,False,False,False,False,False,True,False,True,...,False,False,False,False,True,False,True,True,False,False
neutral,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,False

#### All subjects

In [4]:
subs_all = np.array([x.split('-')[0] + x.split('-')[1] for x in df.columns])
print(len(subs_all))
print(subs_all)

46
['50037L' '50090R' '15294R' '50053R' '50049R' '15737R' '50061R' '14726R'
 '50016L' '14613R' '15358R' '50008L' '16276L' '15441R' '50024R' '14874R'
 '22306R' '14727R' '50033L' '15284R' '50017L' '50029R' '50027L' '50018L'
 '15357R' '50001R' '15006R' '14819R' '14873R' '50034R' '15283R' '50021R'
 '50019R' '15285R' '50020R' '50006R' '50000R' '50007L' '50014R' '14827L'
 '14818R' '14548R' '15882R' '15282R' '50045R' '14685R']

#### Subjects without any bone on bone interference

In [5]:
poses = ['adduction','abduction','flexion','extension','pinch','grasp',
                            'jar','neutral']

mesh2d = np.array(
    [x.split('-')[0]+x.split('-')[1] for x in df.columns[~df[np.isin(df.index, poses)].any()].sort_values().to_list()]
    )

print(len(mesh2d))
print(mesh2d)

36
['14548R' '14613R' '14685R' '14726R' '14727R' '14818R' '14819R' '14827L'
 '14873R' '14874R' '15006R' '15283R' '15294R' '15441R' '15737R' '22306R'
 '50000R' '50001R' '50006R' '50007L' '50008L' '50014R' '50016L' '50017L'
 '50018L' '50019R' '50020R' '50021R' '50024R' '50027L' '50029R' '50034R'
 '50037L' '50045R' '50049R' '50053R']

#### Subjects that fail the cartilage interference check

In [17]:
# path to test run of final params for 
inter_path = '../../../MeshPipeline/outputs/testing/cartilage_update/reports/interference.jsonl'

inter_df = pd.read_json(inter_path, lines=True)
inter_tpm = inter_df.subject[inter_df['bones']=='tpm-mc1'].unique().to_numpy()
inter_mc1 = inter_df.subject[inter_df['bones']=='mc1-tpm'].unique().to_numpy()

ok_tpm = subs_all[~np.isin(subs_all, inter_tpm)]

print('\ntpm')
print(len(inter_tpm))
print(inter_tpm)
print('\nmc1')
print(len(inter_mc1))
print(inter_mc1)

print('\nAll subjects can generate cartilage for both bones or neither bone:', len(np.setxor1d(inter_tpm, inter_mc1))==0)
print('All subjects that pass bone interference check, pass cartilage interference check, and vice versa:', len(np.setxor1d(mesh2d, ok_tpm))==0)

tpm
10
['50090R' '50061R' '15358R' '16276L' '50033L' '15284R' '15357R' '15285R'
 '15882R' '15282R']

mc1
10
['50090R' '50061R' '15358R' '16276L' '50033L' '15284R' '15357R' '15285R'
 '15882R' '15282R']

All subjects can generate cartilage for both bones or neither bone: True
All subjects that pass bone interference check, pass cartilage interference check, and vice versa: True

### Final list

In [ ]:
#pd.DataFrame(np.sort(ok_tpm), columns=['subs_ok']).to_csv('../../../MeshPipeline/subs_ok.csv', index=False)

In [ ]:
subs_ok = pd.read_csv('../../../MeshPipeline/subs_ok.csv').subs_ok.to_list()
subs_ok

   subs_ok
0   14548R
1   14613R
2   14685R
3   14726R
4   14727R
5   14818R
6   14819R
7   14827L
8   14873R
9   14874R
10  15006R
11  15283R
12  15294R
13  15441R
14  15737R
15  22306R
16  50000R
17  50001R
18  50006R
19  50007L
20  50008L
21  50014R
22  50016L
23  50017L
24  50018L
25  50019R
26  50020R
27  50021R
28  50024R
29  50027L
30  50029R
31  50034R
32  50037L
33  50045R
34  50049R
35  50053R

In [27]:
subs_ok.subs_ok.to_list()

['14548R',
 '14613R',
 '14685R',
 '14726R',
 '14727R',
 '14818R',
 '14819R',
 '14827L',
 '14873R',
 '14874R',
 '15006R',
 '15283R',
 '15294R',
 '15441R',
 '15737R',
 '22306R',
 '50000R',
 '50001R',
 '50006R',
 '50007L',
 '50008L',
 '50014R',
 '50016L',
 '50017L',
 '50018L',
 '50019R',
 '50020R',
 '50021R',
 '50024R',
 '50027L',
 '50029R',
 '50034R',
 '50037L',
 '50045R',
 '50049R',
 '50053R']